// Bu dosya `pnpm run gen` tarafından üretilir. ELLE DÜZENLEMEYİN.

export const CAPABILITY_IDS = [
  'actor.capabilities',
  'actor.disconnect',
  'actor.message.read',
  'build.run',
  'events.read',
  'evidence.read',
  'fixture.inspect',
  'logs.read',
  'operation.cancel',
  'operation.read',
  'permission.attach',
  'permission.check',
  'permission.detach',
  'permission.set_op',
  'player.break_block',
  'player.chat',
  'player.look',
  'player.move',
  'player.state.read',
  'plugin.command.typed',
  'plugin.diagnose',
  'plugin.get',
  'plugin.list',
  'pool.acquire',
  'pool.evict',
  'pool.list',
  'pool.release',
  'pool.reset',
  'pool.status',
  'profile.get',
  'profile.list',
  'project.inspect',
  'project.list',
  'project.validate',
  'runtime.create',
  'runtime.delete',
  'runtime.inspect',
  'runtime.launch',
  'runtime.release',
  'runtime.stop',
  'scenario.run',
  'scenario.step_catalog',
  'scenario.validate',
  'server.state.read',
  'system.capabilities',
  'system.health',
  'test_actor.protocol',
  'world.block.read',
  'world.block.write',
  'world.chunk.ticket',
  'world.list',
] as const;

export type CapabilityId = (typeof CAPABILITY_IDS)[number];

export interface CapabilityRisk {
  readonly effect: string;
  readonly scope: string;
  readonly reversibility: string;
  readonly approval: string;
  readonly level: string;
}

export interface CapabilityMeta {
  readonly id: CapabilityId;
  readonly milestone: string;
  readonly status: string;
  readonly summary: string;
  readonly risk: CapabilityRisk;
  readonly developerTool: string | null;
  readonly debugTool: string | null;
  readonly authoringTool: string | null;
  readonly bridgeOperation: string | null;
  readonly dslStep: string | null;
  readonly errors: readonly string[];
}

export const CAPABILITIES: Readonly<Record<CapabilityId, CapabilityMeta>> = {
  'actor.capabilities': {
    id: 'actor.capabilities',
    milestone: 'M2B',
    status: 'conditional',
    summary: "Protocol test actor'ın capability negotiation sonucunu; hangi oyuncu eylemlerinin desteklendiğini bildirir.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: null,
    authoringTool: 'actor_capabilities',
    bridgeOperation: null,
    dslStep: null,
    errors: ['ACTOR_UNAVAILABLE', 'CAPABILITY_UNAVAILABLE'],
  },
  'actor.disconnect': {
    id: 'actor.disconnect',
    milestone: 'M2B',
    status: 'conditional',
    summary: "Scenario cleanup'ında tüm test actor bağlantılarını kapatır.",
    risk: { effect: 'process', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'none', level: 'R1' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'test_actor.disconnect_all',
    dslStep: 'actor.disconnect_all',
    errors: ['CAPABILITY_UNAVAILABLE', 'ACTOR_UNAVAILABLE', 'CLEANUP_FAILED'],
  },
  'actor.message.read': {
    id: 'actor.message.read',
    milestone: 'M2B',
    status: 'conditional',
    summary: "Test actor'a gönderilen mesajları yakalar ve test contract'taki message_key ile eşleştirir.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: null,
    dslStep: 'assert.player_message',
    errors: ['CAPABILITY_UNAVAILABLE', 'ACTOR_UNAVAILABLE', 'PLAYER_NOT_FOUND', 'PLUGIN_CONTRACT_NOT_FOUND'],
  },
  'build.run': {
    id: 'build.run',
    milestone: 'M1',
    status: 'planned',
    summary: "Source snapshot'ı izin verilen execution backend içinde, enum tabanlı bir build moduyla derler.",
    risk: { effect: 'build', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'profile', level: 'R1' },
    developerTool: 'plugin_build',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['PROJECT_NOT_REGISTERED', 'TRUST_LEVEL_INSUFFICIENT', 'SOURCE_CHANGED_DURING_BUILD', 'BACKEND_UNAVAILABLE', 'BACKEND_SECURITY_DOWNGRADE', 'BUILD_MODE_UNSUPPORTED', 'BUILD_FAILED', 'BUILD_TIMEOUT', 'OUTPUT_LIMIT_EXCEEDED', 'DEPENDENCY_VERIFICATION_FAILED', 'DEPENDENCY_LOCK_OUT_OF_DATE', 'ARTIFACT_NOT_FOUND', 'ARTIFACT_PERSIST_FAILED', 'ARTIFACT_AMBIGUOUS', 'JAVA_VERSION_MISMATCH', 'PROVISIONING_APPROVAL_REQUIRED'],
  },
  'events.read': {
    id: 'events.read',
    milestone: 'M0',
    status: 'planned',
    summary: "Boot'a bağlı cursor ile seçilmiş Paper event'lerini sıralı biçimde okur.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: 'minecraft_events_query',
    authoringTool: null,
    bridgeOperation: 'events.query',
    dslStep: 'assert.event',
    errors: ['RUNTIME_NOT_RUNNING', 'EVENT_CURSOR_INSTANCE_MISMATCH', 'EVENT_CURSOR_EXPIRED', 'EVENT_BUFFER_OVERFLOW', 'BRIDGE_TIMEOUT', 'CAPABILITY_UNAVAILABLE'],
  },
  'evidence.read': {
    id: 'evidence.read',
    milestone: 'M1',
    status: 'planned',
    summary: "Kanıt nesnelerini ve birleşik raporu redaction ve byte limiti uygulayarak döndürür.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: 'evidence_get',
    debugTool: null,
    authoringTool: 'evidence_get',
    bridgeOperation: null,
    dslStep: null,
    errors: ['EVIDENCE_NOT_FOUND', 'RESOURCE_NOT_FOUND', 'HANDLE_NOT_OWNED', 'HANDLE_EXPIRED', 'EVIDENCE_INTEGRITY_MISMATCH', 'OUTPUT_LIMIT_EXCEEDED'],
  },
  'fixture.inspect': {
    id: 'fixture.inspect',
    milestone: 'M2A',
    status: 'planned',
    summary: "Fixture manifest'ini, bölgelerini ve izin verilen materyallerini döndürür.",
    risk: { effect: 'read', scope: 'fixture', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: null,
    authoringTool: 'fixture_inspect',
    bridgeOperation: null,
    dslStep: null,
    errors: ['FIXTURE_NOT_FOUND', 'FIXTURE_CHECKSUM_INVALID', 'FIXTURE_PROFILE_MISMATCH'],
  },
  'logs.read': {
    id: 'logs.read',
    milestone: 'M0',
    status: 'planned',
    summary: "Runtime loglarını seviye filtresi, byte ve satır limitiyle redacted biçimde okur.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'logs.query',
    dslStep: 'assert.no_log',
    errors: ['RUNTIME_NOT_RUNNING', 'OUTPUT_LIMIT_EXCEEDED', 'BRIDGE_TIMEOUT', 'CAPABILITY_UNAVAILABLE'],
  },
  'operation.cancel': {
    id: 'operation.cancel',
    milestone: 'M0',
    status: 'planned',
    summary: "Çalışan bir operation'ın iptalini talep eder; iptal kooperatiftir ve terminal durum ayrı raporlanır.",
    risk: { effect: 'process', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R1' },
    developerTool: 'operation_cancel',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['OPERATION_NOT_FOUND', 'OPERATION_NOT_CANCELLABLE', 'HANDLE_NOT_OWNED', 'HANDLE_EXPIRED'],
  },
  'operation.read': {
    id: 'operation.read',
    milestone: 'M0',
    status: 'planned',
    summary: "Uzun süren bir operation'ın durumunu, ilerlemesini ve sonucunu döndürür.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: 'operation_get',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['OPERATION_NOT_FOUND', 'HANDLE_NOT_OWNED', 'HANDLE_EXPIRED'],
  },
  'permission.attach': {
    id: 'permission.attach',
    milestone: 'V1.1',
    status: 'planned',
    summary: "Test actor'una geçici bir izin atar.",
    risk: { effect: 'mutation', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'none', level: 'R2' },
    developerTool: null,
    debugTool: 'permission_attach',
    authoringTool: null,
    bridgeOperation: 'permission.attach',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE', 'PERMISSION_PROVIDER_UNSUPPORTED', 'TOOL_INPUT_INVALID'],
  },
  'permission.check': {
    id: 'permission.check',
    milestone: 'V1.1',
    status: 'planned',
    summary: "Test actor'unun belirtilen izne sahip olup olmadığını kontrol eder.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: 'permission_check',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'permission.check',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE', 'PERMISSION_PROVIDER_UNSUPPORTED', 'TOOL_INPUT_INVALID'],
  },
  'permission.detach': {
    id: 'permission.detach',
    milestone: 'V1.1',
    status: 'planned',
    summary: "Test actor'undan daha önce atanmış bir izni kaldırır.",
    risk: { effect: 'mutation', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'none', level: 'R2' },
    developerTool: null,
    debugTool: 'permission_detach',
    authoringTool: null,
    bridgeOperation: 'permission.detach',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE', 'PERMISSION_PROVIDER_UNSUPPORTED', 'TOOL_INPUT_INVALID'],
  },
  'permission.set_op': {
    id: 'permission.set_op',
    milestone: 'V1.1',
    status: 'planned',
    summary: "Test actor'una operatör statüsü atar veya kaldırır.",
    risk: { effect: 'mutation', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'none', level: 'R2' },
    developerTool: null,
    debugTool: 'permission_set_op',
    authoringTool: null,
    bridgeOperation: 'permission.set_op',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE', 'PERMISSION_PROVIDER_UNSUPPORTED', 'TOOL_INPUT_INVALID'],
  },
  'player.break_block': {
    id: 'player.break_block',
    milestone: 'M2B',
    status: 'conditional',
    summary: "Test actor'a gerçek digging paketleriyle blok kırdırır; iptal semantiği gözlemlenebilir.",
    risk: { effect: 'mutation', scope: 'fixture', reversibility: 'runtime_discard', approval: 'profile', level: 'R2' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'player.break_block',
    dslStep: 'player.break_block',
    errors: ['CAPABILITY_UNAVAILABLE', 'ACTOR_UNAVAILABLE', 'PLAYER_NOT_FOUND', 'REGION_NOT_ALLOWED', 'CHUNK_NOT_LOADED', 'IDEMPOTENCY_KEY_ARGUMENT_MISMATCH', 'MUTATION_UNKNOWN_OUTCOME'],
  },
  'player.chat': {
    id: 'player.chat',
    milestone: 'M2B',
    status: 'conditional',
    summary: "Test actor'ın oyun içi sohbet mesajı göndermesini sağlar; plugin listener'ları gözlemleyebilir.",
    risk: { effect: 'mutation', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'profile', level: 'R2' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'player.chat',
    dslStep: 'player.chat',
    errors: ['CAPABILITY_UNAVAILABLE', 'ACTOR_UNAVAILABLE', 'PLAYER_NOT_FOUND', 'IDEMPOTENCY_KEY_ARGUMENT_MISMATCH', 'MUTATION_UNKNOWN_OUTCOME'],
  },
  'player.look': {
    id: 'player.look',
    milestone: 'M2B',
    status: 'conditional',
    summary: "Test actor'ın bakış yönünü (yaw/pitch) değiştirir.",
    risk: { effect: 'mutation', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'profile', level: 'R2' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'player.look',
    dslStep: 'player.look',
    errors: ['CAPABILITY_UNAVAILABLE', 'ACTOR_UNAVAILABLE', 'PLAYER_NOT_FOUND', 'IDEMPOTENCY_KEY_ARGUMENT_MISMATCH', 'MUTATION_UNKNOWN_OUTCOME'],
  },
  'player.move': {
    id: 'player.move',
    milestone: 'M2B',
    status: 'conditional',
    summary: "Test actor'ı belirtilen dünya ve koordinata ışınlar; teleport gerçek oyuncu olarak işlenir.",
    risk: { effect: 'mutation', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'profile', level: 'R2' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'player.move',
    dslStep: 'player.move',
    errors: ['CAPABILITY_UNAVAILABLE', 'ACTOR_UNAVAILABLE', 'PLAYER_NOT_FOUND', 'IDEMPOTENCY_KEY_ARGUMENT_MISMATCH', 'MUTATION_UNKNOWN_OUTCOME'],
  },
  'player.state.read': {
    id: 'player.state.read',
    milestone: 'M0',
    status: 'planned',
    summary: "Test oyuncusunun konum, dünya, sağlık ve gamemode gibi temel durumunu okur.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: 'minecraft_player_get',
    authoringTool: null,
    bridgeOperation: 'player.get_state',
    dslStep: 'assert.player_state',
    errors: ['RUNTIME_NOT_RUNNING', 'PLAYER_NOT_FOUND', 'BRIDGE_TIMEOUT', 'CAPABILITY_UNAVAILABLE'],
  },
  'plugin.command.typed': {
    id: 'plugin.command.typed',
    milestone: 'M2B',
    status: 'conditional',
    summary: "Plugin test contract'ında tanımlı bir command_id'yi typed argümanlarla gerçek oyuncu olarak çalıştırır.",
    risk: { effect: 'mutation', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'profile', level: 'R2' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'plugin.command',
    dslStep: 'plugin.command',
    errors: ['CAPABILITY_UNAVAILABLE', 'PLUGIN_CONTRACT_NOT_FOUND', 'PLUGIN_CONTRACT_COMMAND_UNKNOWN', 'PLUGIN_CONTRACT_ARGUMENT_INVALID', 'PERMISSION_PROVIDER_UNSUPPORTED', 'ACTOR_UNAVAILABLE', 'IDEMPOTENCY_KEY_ARGUMENT_MISMATCH', 'MUTATION_UNKNOWN_OUTCOME'],
  },
  'plugin.diagnose': {
    id: 'plugin.diagnose',
    milestone: 'M1',
    status: 'planned',
    summary: "Başarısız bir build veya startup için yapılandırılmış teşhis ve önerilen aksiyon üretir.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: 'plugin_diagnose',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['RUN_NOT_FOUND', 'HANDLE_NOT_OWNED', 'HANDLE_EXPIRED', 'EVIDENCE_NOT_FOUND', 'BUILD_NOT_FOUND', 'RUNTIME_NOT_FOUND', 'RUNTIME_CRASHED', 'READY_GATE_FAILED', 'PLUGIN_ENABLE_FAILED', 'SHUTDOWN_TIMEOUT', 'PORT_STILL_BOUND'],
  },
  'plugin.get': {
    id: 'plugin.get',
    milestone: 'M0',
    status: 'planned',
    summary: "Tek bir plugin'in metadata'sını, bağımlılıklarını ve enable durumunu döndürür.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: 'minecraft_plugin_get',
    authoringTool: null,
    bridgeOperation: 'plugin.get',
    dslStep: null,
    errors: ['RUNTIME_NOT_RUNNING', 'PLUGIN_NOT_FOUND', 'BRIDGE_UNAVAILABLE', 'BRIDGE_TIMEOUT', 'CAPABILITY_UNAVAILABLE'],
  },
  'plugin.list': {
    id: 'plugin.list',
    milestone: 'M0',
    status: 'planned',
    summary: "Runtime'da yüklü plugin'leri ve enabled/disabled durumlarını listeler.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: 'minecraft_plugin_list',
    authoringTool: null,
    bridgeOperation: 'plugin.list',
    dslStep: null,
    errors: ['RUNTIME_NOT_RUNNING', 'BRIDGE_UNAVAILABLE', 'BRIDGE_TIMEOUT', 'CAPABILITY_UNAVAILABLE'],
  },
  'pool.acquire': {
    id: 'pool.acquire',
    milestone: 'V1.1',
    status: 'planned',
    summary: "Havuzdan bir runtime edinir.",
    risk: { effect: 'mutation', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'none', level: 'R2' },
    developerTool: null,
    debugTool: 'pool_acquire',
    authoringTool: null,
    bridgeOperation: 'pool.acquire',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE'],
  },
  'pool.evict': {
    id: 'pool.evict',
    milestone: 'V1.1',
    status: 'planned',
    summary: "Havuzdaki bir runtime'ı zorla tahliye eder.",
    risk: { effect: 'delete', scope: 'disposable_runtime', reversibility: 'destructive', approval: 'none', level: 'R4' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'pool.evict',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE', 'SUPERVISOR_UNAVAILABLE'],
  },
  'pool.list': {
    id: 'pool.list',
    milestone: 'V1.1',
    status: 'planned',
    summary: "Havuzdaki runtime'ların listesini döndürür.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: 'pool_list',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'pool.list',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE'],
  },
  'pool.release': {
    id: 'pool.release',
    milestone: 'V1.1',
    status: 'planned',
    summary: "Havuzdaki bir runtime'ı serbest bırakır.",
    risk: { effect: 'mutation', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'none', level: 'R2' },
    developerTool: null,
    debugTool: 'pool_release',
    authoringTool: null,
    bridgeOperation: 'pool.release',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE'],
  },
  'pool.reset': {
    id: 'pool.reset',
    milestone: 'V1.1',
    status: 'planned',
    summary: "Havuzdaki tüm runtime'ları temizler.",
    risk: { effect: 'delete', scope: 'disposable_runtime', reversibility: 'destructive', approval: 'none', level: 'R4' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'pool.reset',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE'],
  },
  'pool.status': {
    id: 'pool.status',
    milestone: 'V1.1',
    status: 'planned',
    summary: "Runtime havuzunun durumunu raporlar.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: 'pool_status',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'pool.status',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE'],
  },
  'profile.get': {
    id: 'profile.get',
    milestone: 'V1.1',
    status: 'planned',
    summary: "Belirtilen uyumluluk profilinin detaylarını döndürür.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: 'profile_get',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'profile.get',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE', 'CONFIG_INVALID'],
  },
  'profile.list': {
    id: 'profile.list',
    milestone: 'V1.1',
    status: 'planned',
    summary: "Mevcut uyumluluk profillerinin listesini döndürür.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: 'profile_list',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'profile.list',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE'],
  },
  'project.inspect': {
    id: 'project.inspect',
    milestone: 'M1',
    status: 'planned',
    summary: "Kayıtlı projenin Gradle wrapper, plugin.yml ve test contract durumunu keşfeder.",
    risk: { effect: 'read', scope: 'project', reversibility: 'reversible', approval: 'profile', level: 'R1' },
    developerTool: 'project_inspect',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['PROJECT_NOT_REGISTERED', 'TRUST_LEVEL_INSUFFICIENT', 'PATH_OUTSIDE_ROOT', 'SYMLINK_NOT_ALLOWED', 'GRADLE_WRAPPER_NOT_FOUND', 'PLUGIN_METADATA_NOT_FOUND', 'PLUGIN_METADATA_AMBIGUOUS'],
  },
  'project.list': {
    id: 'project.list',
    milestone: 'M3',
    status: 'planned',
    summary: "Trust store'daki kayıtlı projeleri listeler (isteğe bağlı project_id filtresiyle).",
    risk: { effect: 'read', scope: 'project', reversibility: 'reversible', approval: 'profile', level: 'R1' },
    developerTool: 'project_list',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'project.list',
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE', 'PROJECT_NOT_REGISTERED'],
  },
  'project.validate': {
    id: 'project.validate',
    milestone: 'M1',
    status: 'planned',
    summary: "Gradle veya Maven wrapper bütünlüğünü, dependency lock/verification durumunu ve Java/Paper/API uyumluluğunu doğrular.",
    risk: { effect: 'read', scope: 'project', reversibility: 'reversible', approval: 'profile', level: 'R1' },
    developerTool: 'project_validate',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['PROJECT_NOT_REGISTERED', 'TRUST_LEVEL_INSUFFICIENT', 'GRADLE_WRAPPER_NOT_FOUND', 'GRADLE_WRAPPER_JAR_UNVERIFIED', 'GRADLE_DISTRIBUTION_URL_UNAPPROVED', 'GRADLE_DISTRIBUTION_CHECKSUM_MISSING', 'GRADLE_DISTRIBUTION_CHECKSUM_INVALID', 'GRADLE_VERSION_INCOMPATIBLE', 'DEPENDENCY_LOCK_MISSING', 'DEPENDENCY_VERIFICATION_MISSING', 'DYNAMIC_DEPENDENCY_FORBIDDEN', 'CHANGING_MODULE_FORBIDDEN', 'UNAPPROVED_REPOSITORY', 'PLUGIN_API_VERSION_MISSING', 'PLUGIN_API_VERSION_INCOMPATIBLE', 'COMPATIBILITY_PROFILE_UNVERIFIED', 'MVN_WRAPPER_NOT_FOUND', 'MVN_WRAPPER_JAR_UNVERIFIED', 'MVN_DISTRIBUTION_URL_UNAPPROVED', 'MVN_DISTRIBUTION_CHECKSUM_MISSING', 'MVN_DISTRIBUTION_CHECKSUM_INVALID', 'MVN_VERSION_INCOMPATIBLE', 'BUILD_SYSTEM_NOT_FOUND', 'BUILD_SYSTEM_AMBIGUOUS'],
  },
  'runtime.create': {
    id: 'runtime.create',
    milestone: 'M1',
    status: 'planned',
    summary: "Paper JAR, Bridge, hedef artifact, fixture ve determinism profilinden disposable runtime image hazırlar. Hedef plugin yalnızca build_id üzerinden çözümlenir; mutlak path kabul edilmez (FS-03).",
    risk: { effect: 'build', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'profile', level: 'R1' },
    developerTool: null,
    debugTool: 'runtime_create',
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['ARTIFACT_NOT_FOUND', 'ARTIFACT_INTEGRITY_MISMATCH', 'BUILD_NOT_FOUND', 'PAPER_JAR_CHECKSUM_INVALID', 'FIXTURE_NOT_FOUND', 'FIXTURE_PROFILE_MISMATCH', 'BACKEND_UNAVAILABLE', 'BACKEND_SECURITY_DOWNGRADE', 'RUNTIME_QUOTA_EXCEEDED', 'DISK_QUOTA_EXCEEDED', 'COMPATIBILITY_PROFILE_UNVERIFIED'],
  },
  'runtime.delete': {
    id: 'runtime.delete',
    milestone: 'M1',
    status: 'planned',
    summary: "Retention süresi geçmiş runtime dizinini dry-run validation sonrasında siler.",
    risk: { effect: 'delete', scope: 'host', reversibility: 'destructive', approval: 'per_call', level: 'R4' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['RUNTIME_NOT_FOUND', 'RUNTIME_INVALID_STATE', 'RUNTIME_MARKER_MISSING', 'PARENT_OWNERSHIP_MISMATCH', 'PATH_OUTSIDE_ROOT', 'SYMLINK_NOT_ALLOWED', 'DELETE_VALIDATION_FAILED'],
  },
  'runtime.inspect': {
    id: 'runtime.inspect',
    milestone: 'M1',
    status: 'planned',
    summary: "Runtime'ın durumunu, sahiplik bilgisini ve Bridge capability manifest'ini döndürür.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: 'runtime_get',
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['RUNTIME_NOT_FOUND', 'HANDLE_NOT_OWNED', 'HANDLE_EXPIRED'],
  },
  'runtime.launch': {
    id: 'runtime.launch',
    milestone: 'M1',
    status: 'planned',
    summary: "Paper process'ini başlatır, Bridge handshake'ini bekler ve ready gate'i doğrular.",
    risk: { effect: 'process', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'profile', level: 'R1' },
    developerTool: 'plugin_launch',
    debugTool: 'runtime_start',
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['RUNTIME_NOT_FOUND', 'RUNTIME_INVALID_STATE', 'HANDLE_NOT_OWNED', 'JAVA_VERSION_MISMATCH', 'PORT_UNAVAILABLE', 'STARTUP_TIMEOUT', 'READY_GATE_FAILED', 'PLUGIN_ENABLE_FAILED', 'PLUGIN_MAIN_CLASS_MISSING', 'PLUGIN_DEPENDENCY_UNSATISFIED', 'PLUGIN_LOADING_CYCLE', 'PLUGIN_NAME_CONFLICT', 'BRIDGE_HANDSHAKE_FAILED', 'RUNTIME_CRASHED'],
  },
  'runtime.release': {
    id: 'runtime.release',
    milestone: 'M1',
    status: 'planned',
    summary: "Durmuş bir runtime'ı retention durumuna geçirir; port ve process serbestliğini kanıta yazar.",
    risk: { effect: 'process', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'none', level: 'R1' },
    developerTool: null,
    debugTool: 'runtime_release',
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['RUNTIME_NOT_FOUND', 'RUNTIME_INVALID_STATE', 'HANDLE_NOT_OWNED', 'CLEANUP_FAILED', 'PORT_STILL_BOUND'],
  },
  'runtime.stop': {
    id: 'runtime.stop',
    milestone: 'M1',
    status: 'planned',
    summary: "Paper'ı graceful biçimde kapatır; timeout aşılırsa force termination ayrı durum ve audit event üretir.",
    risk: { effect: 'process', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'none', level: 'R1' },
    developerTool: 'plugin_stop',
    debugTool: 'runtime_stop',
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['RUNTIME_NOT_FOUND', 'RUNTIME_INVALID_STATE', 'HANDLE_NOT_OWNED', 'PROCESS_OWNERSHIP_MISMATCH', 'SHUTDOWN_TIMEOUT', 'CLEANUP_FAILED'],
  },
  'scenario.run': {
    id: 'scenario.run',
    milestone: 'M2A',
    status: 'planned',
    summary: "Scenario'yu kendi disposable runtime'ında çalıştırır, assertion'ları değerlendirir ve evidence toplar.",
    risk: { effect: 'process', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'profile', level: 'R1' },
    developerTool: 'scenario_run',
    debugTool: null,
    authoringTool: 'scenario_run',
    bridgeOperation: null,
    dslStep: null,
    errors: ['SCENARIO_SCHEMA_INVALID', 'SCENARIO_STEP_NOT_ALLOWED', 'CAPABILITY_UNAVAILABLE', 'SCENARIO_TIMEOUT', 'ASSERTION_FAILED', 'RUNTIME_CRASHED', 'CLEANUP_FAILED', 'EVIDENCE_WRITE_FAILED', 'MUTATION_UNKNOWN_OUTCOME'],
  },
  'scenario.step_catalog': {
    id: 'scenario.step_catalog',
    milestone: 'M2A',
    status: 'planned',
    summary: "Aktif profilde kullanılabilir DSL step'lerini, argüman şemalarını ve risk seviyelerini listeler.",
    risk: { effect: 'read', scope: 'fixture', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: null,
    authoringTool: 'scenario_step_catalog',
    bridgeOperation: null,
    dslStep: null,
    errors: ['CONFIG_INVALID'],
  },
  'scenario.validate': {
    id: 'scenario.validate',
    milestone: 'M2A',
    status: 'planned',
    summary: "Scenario dosyasını şemaya, step allowlist'ine ve mevcut capability'lere karşı doğrular; çalıştırmaz.",
    risk: { effect: 'read', scope: 'fixture', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: 'scenario_validate',
    debugTool: null,
    authoringTool: 'scenario_validate',
    bridgeOperation: null,
    dslStep: null,
    errors: ['SCENARIO_SCHEMA_INVALID', 'SCENARIO_STEP_NOT_ALLOWED', 'SCENARIO_STEP_LIMIT_EXCEEDED', 'CAPABILITY_UNAVAILABLE', 'PLUGIN_CONTRACT_NOT_FOUND', 'PLUGIN_CONTRACT_COMMAND_UNKNOWN', 'FIXTURE_NOT_FOUND'],
  },
  'server.state.read': {
    id: 'server.state.read',
    milestone: 'M0',
    status: 'planned',
    summary: "Paper sürümü, build, tick sayacı, TPS/MSPT ve online oyuncu sayısını okur.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: 'minecraft_server_get',
    authoringTool: null,
    bridgeOperation: 'server.get_state',
    dslStep: null,
    errors: ['RUNTIME_NOT_RUNNING', 'BRIDGE_UNAVAILABLE', 'BRIDGE_BUSY', 'BRIDGE_TIMEOUT', 'CAPABILITY_UNAVAILABLE'],
  },
  'system.capabilities': {
    id: 'system.capabilities',
    milestone: 'M0',
    status: 'planned',
    summary: "Aktif tool profilini, uyumluluk profilini ve protokol sürümlerini bildirir.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: 'system_capabilities',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['CONFIG_INVALID'],
  },
  'system.health': {
    id: 'system.health',
    milestone: 'M0',
    status: 'planned',
    summary: "MCP Server, Supervisor ve yapılandırma sağlığını raporlar.",
    risk: { effect: 'read', scope: 'disposable_runtime', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: 'system_health',
    debugTool: null,
    authoringTool: null,
    bridgeOperation: null,
    dslStep: null,
    errors: ['SUPERVISOR_UNAVAILABLE', 'CONFIG_INVALID'],
  },
  'test_actor.protocol': {
    id: 'test_actor.protocol',
    milestone: 'M2B',
    status: 'conditional',
    summary: "Offline test identity ile gerçek protokol istemcisi bağlar; join/quit yaşam döngüsünü yönetir.",
    risk: { effect: 'process', scope: 'disposable_runtime', reversibility: 'runtime_discard', approval: 'profile', level: 'R1' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'test_actor.create',
    dslStep: 'test_actor.create',
    errors: ['CAPABILITY_UNAVAILABLE', 'ACTOR_UNAVAILABLE', 'ACTOR_LOGIN_FAILED', 'ACTOR_CRASHED', 'RUNTIME_NOT_RUNNING', 'CLEANUP_FAILED'],
  },
  'world.block.read': {
    id: 'world.block.read',
    milestone: 'M0',
    status: 'planned',
    summary: "Fixture bölgesindeki tek bir bloğun materyalini okur.",
    risk: { effect: 'read', scope: 'fixture', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: 'minecraft_world_get_block',
    authoringTool: null,
    bridgeOperation: 'world.get_block',
    dslStep: 'assert.block',
    errors: ['RUNTIME_NOT_RUNNING', 'WORLD_NOT_FOUND', 'REGION_NOT_ALLOWED', 'CHUNK_NOT_LOADED', 'BRIDGE_TIMEOUT', 'CAPABILITY_UNAVAILABLE'],
  },
  'world.block.write': {
    id: 'world.block.write',
    milestone: 'M2A',
    status: 'implemented',
    summary: "Fixture bölgesi içinde tek bir bloğu, izin verilen materyal listesinden bir değere ayarlar.",
    risk: { effect: 'mutation', scope: 'fixture', reversibility: 'runtime_discard', approval: 'profile', level: 'R2' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'world.set_block',
    dslStep: 'world.set_block',
    errors: ['RUNTIME_NOT_RUNNING', 'WORLD_NOT_FOUND', 'REGION_NOT_ALLOWED', 'MATERIAL_NOT_ALLOWED', 'CHUNK_NOT_LOADED', 'IDEMPOTENCY_KEY_ARGUMENT_MISMATCH', 'BRIDGE_BUSY', 'BRIDGE_TIMEOUT', 'MUTATION_UNKNOWN_OUTCOME', 'CAPABILITY_UNAVAILABLE'],
  },
  'world.chunk.ticket': {
    id: 'world.chunk.ticket',
    milestone: 'M2A',
    status: 'planned',
    summary: "Fixture bölgesini açık chunk ticket'ı ile yüklü tutar; deterministic blok assertion'larının ön koşuludur.",
    risk: { effect: 'mutation', scope: 'fixture', reversibility: 'runtime_discard', approval: 'profile', level: 'R2' },
    developerTool: null,
    debugTool: null,
    authoringTool: null,
    bridgeOperation: 'world.set_chunk_ticket',
    dslStep: 'world.set_chunk_ticket',
    errors: ['RUNTIME_NOT_RUNNING', 'WORLD_NOT_FOUND', 'REGION_NOT_ALLOWED', 'BRIDGE_BUSY', 'BRIDGE_TIMEOUT', 'MUTATION_UNKNOWN_OUTCOME', 'CAPABILITY_UNAVAILABLE'],
  },
  'world.list': {
    id: 'world.list',
    milestone: 'M0',
    status: 'planned',
    summary: "Yüklü dünyaları ve fixture bölgelerini listeler.",
    risk: { effect: 'read', scope: 'fixture', reversibility: 'reversible', approval: 'none', level: 'R0' },
    developerTool: null,
    debugTool: 'minecraft_world_list',
    authoringTool: null,
    bridgeOperation: 'world.list',
    dslStep: null,
    errors: ['RUNTIME_NOT_RUNNING', 'BRIDGE_UNAVAILABLE', 'BRIDGE_TIMEOUT', 'CAPABILITY_UNAVAILABLE'],
  },
} as const;

/** Tool adı -> capability id. Aynı tool adı iki capability'de kullanılamaz
 *  (scripts/validate-registry.mjs kuralı 8), bu yüzden eşleme tekil. */
export const TOOL_TO_CAPABILITY: Readonly<Record<string, CapabilityId>> = {
  'actor_capabilities': 'actor.capabilities',
  'evidence_get': 'evidence.read',
  'fixture_inspect': 'fixture.inspect',
  'minecraft_events_query': 'events.read',
  'minecraft_player_get': 'player.state.read',
  'minecraft_plugin_get': 'plugin.get',
  'minecraft_plugin_list': 'plugin.list',
  'minecraft_server_get': 'server.state.read',
  'minecraft_world_get_block': 'world.block.read',
  'minecraft_world_list': 'world.list',
  'operation_cancel': 'operation.cancel',
  'operation_get': 'operation.read',
  'permission_attach': 'permission.attach',
  'permission_check': 'permission.check',
  'permission_detach': 'permission.detach',
  'permission_set_op': 'permission.set_op',
  'plugin_build': 'build.run',
  'plugin_diagnose': 'plugin.diagnose',
  'plugin_launch': 'runtime.launch',
  'plugin_stop': 'runtime.stop',
  'pool_acquire': 'pool.acquire',
  'pool_list': 'pool.list',
  'pool_release': 'pool.release',
  'pool_status': 'pool.status',
  'profile_get': 'profile.get',
  'profile_list': 'profile.list',
  'project_inspect': 'project.inspect',
  'project_list': 'project.list',
  'project_validate': 'project.validate',
  'runtime_create': 'runtime.create',
  'runtime_get': 'runtime.inspect',
  'runtime_release': 'runtime.release',
  'runtime_start': 'runtime.launch',
  'runtime_stop': 'runtime.stop',
  'scenario_run': 'scenario.run',
  'scenario_step_catalog': 'scenario.step_catalog',
  'scenario_validate': 'scenario.validate',
  'system_capabilities': 'system.capabilities',
  'system_health': 'system.health',
} as const;
