// Bu dosya `pnpm run gen` tarafından üretilir. ELLE DÜZENLEMEYİN.

export const ERROR_CODES = [
  'ACTOR_CRASHED',
  'ACTOR_LOGIN_FAILED',
  'ACTOR_UNAVAILABLE',
  'ARCHIVE_ENTRY_OUTSIDE_ROOT',
  'ARCHIVE_EXPANSION_LIMIT',
  'ARTIFACT_AMBIGUOUS',
  'ARTIFACT_INTEGRITY_MISMATCH',
  'ARTIFACT_NOT_FOUND',
  'ARTIFACT_PERSIST_FAILED',
  'ASSERTION_FAILED',
  'BACKEND_SECURITY_DOWNGRADE',
  'BACKEND_UNAVAILABLE',
  'BODY_TOO_LARGE',
  'BRIDGE_BUSY',
  'BRIDGE_HANDSHAKE_FAILED',
  'BRIDGE_ORIGIN_REJECTED',
  'BRIDGE_TIMEOUT',
  'BRIDGE_UNAUTHORIZED',
  'BRIDGE_UNAVAILABLE',
  'BUILD_FAILED',
  'BUILD_MODE_UNSUPPORTED',
  'BUILD_NOT_FOUND',
  'BUILD_TIMEOUT',
  'CAPABILITY_UNAVAILABLE',
  'CHANGING_MODULE_FORBIDDEN',
  'CHUNK_NOT_LOADED',
  'CLEANUP_FAILED',
  'COMPATIBILITY_PROFILE_MISMATCH',
  'COMPATIBILITY_PROFILE_UNVERIFIED',
  'CONFIG_INVALID',
  'CONFIG_VERSION_UNSUPPORTED',
  'DELETE_VALIDATION_FAILED',
  'DEPENDENCY_LOCK_MISSING',
  'DEPENDENCY_LOCK_OUT_OF_DATE',
  'DEPENDENCY_VERIFICATION_FAILED',
  'DEPENDENCY_VERIFICATION_MISSING',
  'DIRTY_WORKSPACE_REJECTED',
  'DISK_QUOTA_EXCEEDED',
  'DYNAMIC_DEPENDENCY_FORBIDDEN',
  'ENVIRONMENT_VARIABLE_NOT_ALLOWED',
  'EULA_NOT_ACCEPTED',
  'EVENT_BUFFER_OVERFLOW',
  'EVENT_CURSOR_EXPIRED',
  'EVENT_CURSOR_INSTANCE_MISMATCH',
  'EVIDENCE_INTEGRITY_MISMATCH',
  'EVIDENCE_NOT_FOUND',
  'EVIDENCE_WRITE_FAILED',
  'FIXTURE_CHECKSUM_INVALID',
  'FIXTURE_NOT_FOUND',
  'FIXTURE_PROFILE_MISMATCH',
  'GRADLE_DISTRIBUTION_CHECKSUM_INVALID',
  'GRADLE_DISTRIBUTION_CHECKSUM_MISSING',
  'GRADLE_DISTRIBUTION_URL_UNAPPROVED',
  'GRADLE_VERSION_INCOMPATIBLE',
  'GRADLE_WRAPPER_JAR_UNVERIFIED',
  'GRADLE_WRAPPER_NOT_FOUND',
  'HANDLE_EXPIRED',
  'HANDLE_NOT_OWNED',
  'IDEMPOTENCY_KEY_ARGUMENT_MISMATCH',
  'JAVA_VERSION_MISMATCH',
  'MATERIAL_NOT_ALLOWED',
  'MUTATION_UNKNOWN_OUTCOME',
  'MVN_DISTRIBUTION_CHECKSUM_INVALID',
  'MVN_DISTRIBUTION_CHECKSUM_MISSING',
  'MVN_DISTRIBUTION_URL_UNAPPROVED',
  'MVN_VERSION_INCOMPATIBLE',
  'MVN_WRAPPER_JAR_UNVERIFIED',
  'MVN_WRAPPER_NOT_FOUND',
  'OPERATION_NOT_CANCELLABLE',
  'OPERATION_NOT_FOUND',
  'OUTPUT_LIMIT_EXCEEDED',
  'PAPER_JAR_CHECKSUM_INVALID',
  'PAPER_PLUGIN_EXPERIMENTAL_DISABLED',
  'PARENT_OWNERSHIP_MISMATCH',
  'PATH_OUTSIDE_ROOT',
  'PERMISSION_PROVIDER_UNSUPPORTED',
  'PLAYER_NOT_FOUND',
  'PLUGIN_API_VERSION_INCOMPATIBLE',
  'PLUGIN_API_VERSION_MISSING',
  'PLUGIN_CONTRACT_ARGUMENT_INVALID',
  'PLUGIN_CONTRACT_COMMAND_UNKNOWN',
  'PLUGIN_CONTRACT_NOT_FOUND',
  'PLUGIN_DEPENDENCY_UNSATISFIED',
  'PLUGIN_ENABLE_FAILED',
  'PLUGIN_LOADING_CYCLE',
  'PLUGIN_MAIN_CLASS_MISSING',
  'PLUGIN_METADATA_AMBIGUOUS',
  'PLUGIN_METADATA_NOT_FOUND',
  'PLUGIN_NAME_CONFLICT',
  'PLUGIN_NOT_FOUND',
  'PORT_STILL_BOUND',
  'PORT_UNAVAILABLE',
  'PROCESS_OWNERSHIP_MISMATCH',
  'PROJECT_NOT_REGISTERED',
  'PROVISIONING_APPROVAL_REQUIRED',
  'READY_GATE_FAILED',
  'REGION_NOT_ALLOWED',
  'RESOURCE_NOT_FOUND',
  'RUNTIME_CRASHED',
  'RUNTIME_INVALID_STATE',
  'RUNTIME_MARKER_MISSING',
  'RUNTIME_NOT_FOUND',
  'RUNTIME_NOT_RUNNING',
  'RUNTIME_QUOTA_EXCEEDED',
  'RUN_NOT_FOUND',
  'SCENARIO_SCHEMA_INVALID',
  'SCENARIO_STEP_LIMIT_EXCEEDED',
  'SCENARIO_STEP_NOT_ALLOWED',
  'SCENARIO_TIMEOUT',
  'SHUTDOWN_TIMEOUT',
  'SOURCE_CHANGED_DURING_BUILD',
  'STARTUP_TIMEOUT',
  'SUPERVISOR_UNAVAILABLE',
  'SYMLINK_NOT_ALLOWED',
  'TOOL_INPUT_INVALID',
  'TRUST_LEVEL_INSUFFICIENT',
  'UNAPPROVED_REPOSITORY',
  'UNKNOWN_TOOL',
  'WORLD_NOT_FOUND',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export interface ErrorMeta {
  readonly code: ErrorCode;
  readonly owner: string;
  readonly category: string;
  readonly message: string;
  readonly retryable: boolean;
  readonly suggestedAction: string;
  readonly protocolError: boolean;
  readonly httpStatus: number | null;
  readonly redactionProfile: string;
  readonly terminalState: string | null;
}

export const ERRORS: Readonly<Record<ErrorCode, ErrorMeta>> = {
  ACTOR_CRASHED: {
    code: 'ACTOR_CRASHED',
    owner: 'actor',
    category: 'internal',
    message: "Test actor process'i beklenmedik biçimde sonlandı.",
    retryable: false,
    suggestedAction: "evidence_get ile actor transcript'ini inceleyin; Paper tarafında kalan oyuncu için cleanup kanıtını kontrol edin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: 'FAILED',
  },
  ACTOR_LOGIN_FAILED: {
    code: 'ACTOR_LOGIN_FAILED',
    owner: 'actor',
    category: 'state',
    message: "Test actor sunucuya giriş yapamadı.",
    retryable: true,
    suggestedAction: "Determinism profilinde online_mode: false olduğunu ve runtime'ın READY durumunda olduğunu doğrulayın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: null,
  },
  ACTOR_UNAVAILABLE: {
    code: 'ACTOR_UNAVAILABLE',
    owner: 'actor',
    category: 'environment',
    message: "Protocol test actor bu kurulumda kullanılamıyor.",
    retryable: false,
    suggestedAction: "actor_capabilities ile desteklenen eylemleri kontrol edin; M2B koşullu bir milestone'dur.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  ARCHIVE_ENTRY_OUTSIDE_ROOT: {
    code: 'ARCHIVE_ENTRY_OUTSIDE_ROOT',
    owner: 'security',
    category: 'permission',
    message: "Arşiv girdisi hedef kökün dışına çıkıyor.",
    retryable: false,
    suggestedAction: "Arşivi güvenilir bir kaynaktan yeniden üretin; traversal içeren arşiv açılmaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: null,
  },
  ARCHIVE_EXPANSION_LIMIT: {
    code: 'ARCHIVE_EXPANSION_LIMIT',
    owner: 'security',
    category: 'limit',
    message: "Arşiv açılım boyutu veya sıkıştırma oranı limiti aşıldı.",
    retryable: false,
    suggestedAction: "Arşiv içeriğini küçültün; aşırı sıkıştırma oranı zip bomb koruması tarafından reddedilir.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  ARTIFACT_AMBIGUOUS: {
    code: 'ARTIFACT_AMBIGUOUS',
    owner: 'build',
    category: 'conflict',
    message: "Birden fazla aday artifact bulundu; deterministik seçim yapılamadı.",
    retryable: false,
    suggestedAction: "Tek bir plugin JAR'ı üretin veya proje test contract'ında beklenen artifact adını belirtin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: 'FAILED',
  },
  ARTIFACT_INTEGRITY_MISMATCH: {
    code: 'ARTIFACT_INTEGRITY_MISMATCH',
    owner: 'build',
    category: 'integrity',
    message: "Build artifact'ı kayıt anındaki sha256 ile eşleşmiyor; dosya sonradan değiştirilmiş.",
    retryable: false,
    suggestedAction: "Artifact'ı el ile değiştirmeyin; kaynağı yeniden build edip yeni build_id ile kullanın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: 'FAILED',
  },
  ARTIFACT_NOT_FOUND: {
    code: 'ARTIFACT_NOT_FOUND',
    owner: 'build',
    category: 'not_found',
    message: "Build çıktısında beklenen plugin JAR'ı bulunamadı.",
    retryable: false,
    suggestedAction: "Gradle jar/shadowJar task'ının çıktı dizinini kontrol edin; artifact yalnızca doğrulanmış build output'u altından seçilir.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: 'FAILED',
  },
  ARTIFACT_PERSIST_FAILED: {
    code: 'ARTIFACT_PERSIST_FAILED',
    owner: 'build',
    category: 'internal',
    message: "Build artifact'ı kalıcı depoya kopyalanamadı.",
    retryable: true,
    suggestedAction: "Artifact deposunun (.mcpdev-data/artifacts) yazılabilir olduğunu doğrulayın ve build'i tekrarlayın; build kaydı silinen geçici dosyalara bağlanamaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: 'FAILED',
  },
  ASSERTION_FAILED: {
    code: 'ASSERTION_FAILED',
    owner: 'scenario',
    category: 'state',
    message: "Bir veya daha fazla assertion başarısız.",
    retryable: false,
    suggestedAction: "evidence_get ile expected/observed değerlerini ve ilgili event/log kanıtlarını inceleyin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: null,
  },
  BACKEND_SECURITY_DOWNGRADE: {
    code: 'BACKEND_SECURITY_DOWNGRADE',
    owner: 'build',
    category: 'permission',
    message: "Runtime backend'i build backend'inden daha zayıf bir izolasyon sınıfında.",
    retryable: false,
    suggestedAction: "Runtime'ı build ile aynı veya daha güçlü backend'de başlatın; Container'da build edilen artifact Trusted Local'de çalıştırılamaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  BACKEND_UNAVAILABLE: {
    code: 'BACKEND_UNAVAILABLE',
    owner: 'build',
    category: 'environment',
    message: "İstenen execution backend kullanılamıyor.",
    retryable: true,
    suggestedAction: "Container runtime'ının çalıştığını doğrulayın veya projenin allowed_backends listesinden kullanılabilir bir backend seçin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: null,
  },
  BODY_TOO_LARGE: {
    code: 'BODY_TOO_LARGE',
    owner: 'bridge',
    category: 'limit',
    message: "İstek gövdesi izin verilen boyutu aşıyor.",
    retryable: false,
    suggestedAction: "İsteği bölün; security.max_request_body_bytes limitini aşan gövde işlenmez.",
    protocolError: false,
    httpStatus: 413,
    redactionProfile: 'none',
    terminalState: null,
  },
  BRIDGE_BUSY: {
    code: 'BRIDGE_BUSY',
    owner: 'bridge',
    category: 'limit',
    message: "Bridge worker kuyruğu dolu.",
    retryable: true,
    suggestedAction: "Kısa bir bekleme sonrası tekrar deneyin; salt okuma istekleri sınırlı biçimde retry edilebilir.",
    protocolError: false,
    httpStatus: 429,
    redactionProfile: 'none',
    terminalState: null,
  },
  BRIDGE_HANDSHAKE_FAILED: {
    code: 'BRIDGE_HANDSHAKE_FAILED',
    owner: 'bridge',
    category: 'integrity',
    message: "Bridge handshake tamamlanamadı.",
    retryable: false,
    suggestedAction: "Runtime loglarında Bridge yükleme hatasını inceleyin; handshake dosyası port ve protokol metadata'sı taşır, secret taşımaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: 'FAILED',
  },
  BRIDGE_ORIGIN_REJECTED: {
    code: 'BRIDGE_ORIGIN_REJECTED',
    owner: 'bridge',
    category: 'permission',
    message: "Host veya Origin başlığı reddedildi.",
    retryable: false,
    suggestedAction: "Bridge'e yalnızca loopback üzerinden, doğru Host başlığıyla bağlanın; tarayıcı kaynaklı istekler reddedilir.",
    protocolError: false,
    httpStatus: 403,
    redactionProfile: 'default-v1',
    terminalState: null,
  },
  BRIDGE_TIMEOUT: {
    code: 'BRIDGE_TIMEOUT',
    owner: 'bridge',
    category: 'timeout',
    message: "Bridge operation'ı süre limitini aştı.",
    retryable: false,
    suggestedAction: "Salt okuma isteklerini tekrar deneyebilirsiniz; mutation için önce mutation durumunu sorgulayın.",
    protocolError: false,
    httpStatus: 504,
    redactionProfile: 'none',
    terminalState: null,
  },
  BRIDGE_UNAUTHORIZED: {
    code: 'BRIDGE_UNAUTHORIZED',
    owner: 'bridge',
    category: 'permission',
    message: "Bridge isteği kimlik doğrulamasından geçemedi.",
    retryable: false,
    suggestedAction: "Runtime'ın kendi token'ını kullanın; her runtime için ayrı token üretilir ve kısa TTL taşır.",
    protocolError: false,
    httpStatus: 401,
    redactionProfile: 'strict-v1',
    terminalState: null,
  },
  BRIDGE_UNAVAILABLE: {
    code: 'BRIDGE_UNAVAILABLE',
    owner: 'bridge',
    category: 'environment',
    message: "Paper Bridge'e ulaşılamıyor.",
    retryable: true,
    suggestedAction: "runtime_get ile Bridge handshake durumunu kontrol edin; Bridge plugin'inin yüklendiğini doğrulayın.",
    protocolError: false,
    httpStatus: 503,
    redactionProfile: 'default-v1',
    terminalState: null,
  },
  BUILD_FAILED: {
    code: 'BUILD_FAILED',
    owner: 'build',
    category: 'internal',
    message: "Build başarısız oldu.",
    retryable: false,
    suggestedAction: "plugin_diagnose ile dosya, satır ve sembol düzeyindeki derleyici teşhisini alın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: 'FAILED',
  },
  BUILD_MODE_UNSUPPORTED: {
    code: 'BUILD_MODE_UNSUPPORTED',
    owner: 'build',
    category: 'validation',
    message: "İstenen build modu desteklenmiyor.",
    retryable: false,
    suggestedAction: "build | unit_test | integration_test | clean_build modlarından birini seçin; serbest Gradle task verilemez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  BUILD_NOT_FOUND: {
    code: 'BUILD_NOT_FOUND',
    owner: 'build',
    category: 'not_found',
    message: "Belirtilen build kaydı bulunamadı.",
    retryable: false,
    suggestedAction: "build_id'yi plugin_build sonucundan doğrulayın; build kayıtları bellekte tutulur, süreç yeniden başladıysa kaybolmuştur.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  BUILD_TIMEOUT: {
    code: 'BUILD_TIMEOUT',
    owner: 'build',
    category: 'timeout',
    message: "Build yapılandırılmış süre limitini aştı.",
    retryable: true,
    suggestedAction: "build.timeout_seconds değerini artırın veya clean_build yerine artımlı build kullanın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'TIMED_OUT',
  },
  CAPABILITY_UNAVAILABLE: {
    code: 'CAPABILITY_UNAVAILABLE',
    owner: 'mcp',
    category: 'state',
    message: "Bu tool'un gerektirdiği capability aktif runtime'da mevcut değil.",
    retryable: false,
    suggestedAction: "system_capabilities veya runtime_get ile mevcut capability'leri kontrol edin; M2B kapalıysa actor gerektiren adımları kullanmayın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  CHANGING_MODULE_FORBIDDEN: {
    code: 'CHANGING_MODULE_FORBIDDEN',
    owner: 'gradle',
    category: 'validation',
    message: "Changing module veya SNAPSHOT bağımlılığı release profilinde yasak.",
    retryable: false,
    suggestedAction: "SNAPSHOT bağımlılıklarını yayınlanmış sürümlerle değiştirin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  CHUNK_NOT_LOADED: {
    code: 'CHUNK_NOT_LOADED',
    owner: 'bridge',
    category: 'state',
    message: "Hedef chunk yüklü değil.",
    retryable: true,
    suggestedAction: "Fixture bölgesi içinde kalın; view_distance ve simulation_distance determinism profilinde sabittir.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  CLEANUP_FAILED: {
    code: 'CLEANUP_FAILED',
    owner: 'supervisor',
    category: 'integrity',
    message: "Cleanup tamamlanamadı; ana sonuç ayrı raporlanır.",
    retryable: true,
    suggestedAction: "Rapordaki cleanup alanını inceleyin; kalan process ve port için runtime_get çalıştırın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: 'DIRTY',
  },
  COMPATIBILITY_PROFILE_MISMATCH: {
    code: 'COMPATIBILITY_PROFILE_MISMATCH',
    owner: 'config',
    category: 'validation',
    message: "Ortamda bulunan sürüm uyumluluk profiliyle eşleşmiyor.",
    retryable: false,
    suggestedAction: "system_health çıktısındaki uyuşmayan bileşeni profildeki sürüme getirin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  COMPATIBILITY_PROFILE_UNVERIFIED: {
    code: 'COMPATIBILITY_PROFILE_UNVERIFIED',
    owner: 'config',
    category: 'integrity',
    message: "Uyumluluk profili doğrulanmamış durumda.",
    retryable: false,
    suggestedAction: "pnpm run verify:compatibility çalıştırın; doğrulanmamış profille release build üretilemez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  CONFIG_INVALID: {
    code: 'CONFIG_INVALID',
    owner: 'config',
    category: 'validation',
    message: "Ürün yapılandırması şemaya uymuyor.",
    retryable: false,
    suggestedAction: "Config dosyasını config.schema.json'a göre düzeltin; bilinmeyen property hata üretir.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: null,
  },
  CONFIG_VERSION_UNSUPPORTED: {
    code: 'CONFIG_VERSION_UNSUPPORTED',
    owner: 'config',
    category: 'validation',
    message: "Config schema sürümü desteklenmiyor.",
    retryable: false,
    suggestedAction: "Migration notlarını izleyerek config'i desteklenen sürüme yükseltin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  DELETE_VALIDATION_FAILED: {
    code: 'DELETE_VALIDATION_FAILED',
    owner: 'supervisor',
    category: 'integrity',
    message: "Silme öncesi dry-run doğrulaması başarısız.",
    retryable: false,
    suggestedAction: "Garbage Collector loglarını inceleyin; doğrulama geçmeden silme başlamaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: null,
  },
  DEPENDENCY_LOCK_MISSING: {
    code: 'DEPENDENCY_LOCK_MISSING',
    owner: 'gradle',
    category: 'integrity',
    message: "Dependency lock dosyası bulunamadı.",
    retryable: false,
    suggestedAction: "Onaylı provisioning workflow'u ile lock dosyalarını üretin; release profilinde lock zorunludur.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  DEPENDENCY_LOCK_OUT_OF_DATE: {
    code: 'DEPENDENCY_LOCK_OUT_OF_DATE',
    owner: 'gradle',
    category: 'integrity',
    message: "Lock dosyası mevcut bağımlılıklarla uyuşmuyor.",
    retryable: false,
    suggestedAction: "Onaylı provisioning workflow'u ile lock dosyasını güncelleyin; lock drift CI hatasıdır.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  DEPENDENCY_VERIFICATION_FAILED: {
    code: 'DEPENDENCY_VERIFICATION_FAILED',
    owner: 'gradle',
    category: 'integrity',
    message: "Bir bağımlılığın checksum veya imza doğrulaması başarısız.",
    retryable: false,
    suggestedAction: "Bağımlılığın kaynağını inceleyin; doğrulanamayan bağımlılıkla build çalıştırılmaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  DEPENDENCY_VERIFICATION_MISSING: {
    code: 'DEPENDENCY_VERIFICATION_MISSING',
    owner: 'gradle',
    category: 'integrity',
    message: "gradle/verification-metadata.xml bulunamadı.",
    retryable: false,
    suggestedAction: "Verification metadata'yı provisioning modunda üretin ve manuel review'dan geçirin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  DIRTY_WORKSPACE_REJECTED: {
    code: 'DIRTY_WORKSPACE_REJECTED',
    owner: 'project',
    category: 'validation',
    message: "CI profilinde kirli workspace kabul edilmez.",
    retryable: false,
    suggestedAction: "Değişiklikleri commit edin veya pinned-source trust seviyesi ile sabit bir commit kullanın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  DISK_QUOTA_EXCEEDED: {
    code: 'DISK_QUOTA_EXCEEDED',
    owner: 'supervisor',
    category: 'limit',
    message: "Yapılandırılmış disk kotası aşıldı.",
    retryable: false,
    suggestedAction: "Retention süresini kısaltın veya storage.max_total_gb değerini artırın; Garbage Collector'ın çalıştığını doğrulayın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  DYNAMIC_DEPENDENCY_FORBIDDEN: {
    code: 'DYNAMIC_DEPENDENCY_FORBIDDEN',
    owner: 'gradle',
    category: 'validation',
    message: "Dinamik sürüm ifadesi kullanılmış.",
    retryable: false,
    suggestedAction: "Sürüm aralıklarını ve + ifadelerini sabit sürümlerle değiştirin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  ENVIRONMENT_VARIABLE_NOT_ALLOWED: {
    code: 'ENVIRONMENT_VARIABLE_NOT_ALLOWED',
    owner: 'security',
    category: 'permission',
    message: "Environment değişkeni allowlist dışında.",
    retryable: false,
    suggestedAction: "Gerekli değişkeni ürün config'indeki environment allowlist'ine ekleyin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: null,
  },
  EULA_NOT_ACCEPTED: {
    code: 'EULA_NOT_ACCEPTED',
    owner: 'runtime',
    category: 'permission',
    message: "Minecraft EULA kabul edilmeden runtime oluşturulamaz.",
    retryable: false,
    suggestedAction: "Kullanıcıdan `mcpdev eula accept` çalıştırmasını isteyin. Bu, https://aka.ms/MinecraftEULA adresindeki sözleşmeyi kabul ettiğiniz anlamına gelir; ürün bu kararı sizin adınıza vermez ve ajan kabul edemez.",
    protocolError: false,
    httpStatus: 403,
    redactionProfile: 'none',
    terminalState: null,
  },
  EVENT_BUFFER_OVERFLOW: {
    code: 'EVENT_BUFFER_OVERFLOW',
    owner: 'bridge',
    category: 'limit',
    message: "Event ring buffer taştı; event kaybı oldu.",
    retryable: false,
    suggestedAction: "Event drop metriğini inceleyin; scenario'yu daha az event üreten bir fixture ile çalıştırın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  EVENT_CURSOR_EXPIRED: {
    code: 'EVENT_CURSOR_EXPIRED',
    owner: 'bridge',
    category: 'state',
    message: "Cursor'ın işaret ettiği sequence ring buffer'dan düşmüş.",
    retryable: false,
    suggestedAction: "Daha sık poll edin veya daha dar bir aralık sorgulayın; kaçırılan event'ler geri getirilemez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  EVENT_CURSOR_INSTANCE_MISMATCH: {
    code: 'EVENT_CURSOR_INSTANCE_MISMATCH',
    owner: 'bridge',
    category: 'conflict',
    message: "Cursor başka bir server instance veya Bridge boot'una ait.",
    retryable: false,
    suggestedAction: "Mevcut server_instance_id ve bridge_boot_id ile yeni bir cursor alın; eski cursor sessizce sıfırlanmaz.",
    protocolError: false,
    httpStatus: 409,
    redactionProfile: 'none',
    terminalState: null,
  },
  EVIDENCE_INTEGRITY_MISMATCH: {
    code: 'EVIDENCE_INTEGRITY_MISMATCH',
    owner: 'evidence',
    category: 'integrity',
    message: "Evidence checksum'ı manifest değeriyle eşleşmiyor veya provenance zinciri eksik.",
    retryable: false,
    suggestedAction: "Raporu kanıt olarak kullanmayın ve run'ı tekrarlayın; eksik provenance zinciri sessizce tolere edilmez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  EVIDENCE_NOT_FOUND: {
    code: 'EVIDENCE_NOT_FOUND',
    owner: 'evidence',
    category: 'not_found',
    message: "Belirtilen evidence nesnesi bulunamadı.",
    retryable: false,
    suggestedAction: "Rapordaki evidence_ids listesini kullanın; retention süresi geçmiş kanıtlar silinmiş olabilir.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  EVIDENCE_WRITE_FAILED: {
    code: 'EVIDENCE_WRITE_FAILED',
    owner: 'evidence',
    category: 'internal',
    message: "Evidence yazma işlemi başarısız.",
    retryable: true,
    suggestedAction: "Disk alanını ve storage.evidence_root izinlerini kontrol edin; yazma atomic temp-write + rename ile yapılır.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: 'FAILED',
  },
  FIXTURE_CHECKSUM_INVALID: {
    code: 'FIXTURE_CHECKSUM_INVALID',
    owner: 'scenario',
    category: 'integrity',
    message: "Fixture içeriği manifest checksum'ı ile eşleşmiyor.",
    retryable: false,
    suggestedAction: "Fixture'ı repository'den yeniden alın; değiştirilmiş fixture determinizmi bozar.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  FIXTURE_NOT_FOUND: {
    code: 'FIXTURE_NOT_FOUND',
    owner: 'scenario',
    category: 'not_found',
    message: "Belirtilen fixture bulunamadı.",
    retryable: false,
    suggestedAction: "fixture_inspect ile mevcut fixture kimliklerini listeleyin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  FIXTURE_PROFILE_MISMATCH: {
    code: 'FIXTURE_PROFILE_MISMATCH',
    owner: 'scenario',
    category: 'validation',
    message: "Fixture bu uyumluluk profilini desteklemiyor.",
    retryable: false,
    suggestedAction: "Fixture manifest'indeki supported_profile değerini kontrol edin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  GRADLE_DISTRIBUTION_CHECKSUM_INVALID: {
    code: 'GRADLE_DISTRIBUTION_CHECKSUM_INVALID',
    owner: 'gradle',
    category: 'integrity',
    message: "Gradle dağıtımının checksum'ı beklenen değerle eşleşmiyor.",
    retryable: false,
    suggestedAction: "Dağıtımı yeniden indirin ve resmî checksum ile karşılaştırın; eşleşmeyen dağıtım kullanılmaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  GRADLE_DISTRIBUTION_CHECKSUM_MISSING: {
    code: 'GRADLE_DISTRIBUTION_CHECKSUM_MISSING',
    owner: 'gradle',
    category: 'integrity',
    message: "distributionSha256Sum tanımlı değil.",
    retryable: false,
    suggestedAction: "gradle-wrapper.properties dosyasına distributionSha256Sum ekleyin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  GRADLE_DISTRIBUTION_URL_UNAPPROVED: {
    code: 'GRADLE_DISTRIBUTION_URL_UNAPPROVED',
    owner: 'gradle',
    category: 'permission',
    message: "distributionUrl allowlist dışında.",
    retryable: false,
    suggestedAction: "distributionUrl değerini services.gradle.org üzerindeki resmî dağıtıma çevirin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  GRADLE_VERSION_INCOMPATIBLE: {
    code: 'GRADLE_VERSION_INCOMPATIBLE',
    owner: 'gradle',
    category: 'validation',
    message: "Wrapper sürümü uyumluluk profilindeki sürümle eşleşmiyor.",
    retryable: false,
    suggestedAction: "Wrapper'ı profildeki Gradle sürümüne güncelleyin; release profili farklı sürüme izin vermez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  GRADLE_WRAPPER_JAR_UNVERIFIED: {
    code: 'GRADLE_WRAPPER_JAR_UNVERIFIED',
    owner: 'gradle',
    category: 'integrity',
    message: "gradle-wrapper.jar checksum doğrulaması başarısız.",
    retryable: false,
    suggestedAction: "Wrapper'ı resmî Gradle dağıtımından yeniden üretin; doğrulanmamış wrapper JAR ile build çalıştırılmaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  GRADLE_WRAPPER_NOT_FOUND: {
    code: 'GRADLE_WRAPPER_NOT_FOUND',
    owner: 'gradle',
    category: 'not_found',
    message: "Gradle Wrapper dosyaları bulunamadı.",
    retryable: false,
    suggestedAction: "gradlew, gradle-wrapper.jar ve gradle-wrapper.properties dosyalarını projeye ekleyin; yalnızca wrapper desteklenir.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  HANDLE_EXPIRED: {
    code: 'HANDLE_EXPIRED',
    owner: 'mcp',
    category: 'state',
    message: "Kimliğin TTL süresi geçmiş.",
    retryable: false,
    suggestedAction: "İlgili kaynağı yeniden oluşturun; süresi geçmiş kimlik sessizce kabul edilmez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  HANDLE_NOT_OWNED: {
    code: 'HANDLE_NOT_OWNED',
    owner: 'mcp',
    category: 'permission',
    message: "Bu kimlik çağıran bağlama ait değil.",
    retryable: false,
    suggestedAction: "Kendi run/operation kimliklerinizi kullanın; kimliğe sahip olmak yetki anlamına gelmez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: null,
  },
  IDEMPOTENCY_KEY_ARGUMENT_MISMATCH: {
    code: 'IDEMPOTENCY_KEY_ARGUMENT_MISMATCH',
    owner: 'bridge',
    category: 'conflict',
    message: "Aynı idempotency key farklı argümanlarla kullanıldı.",
    retryable: false,
    suggestedAction: "Her farklı mutation için yeni bir idempotency key üretin.",
    protocolError: false,
    httpStatus: 409,
    redactionProfile: 'none',
    terminalState: null,
  },
  JAVA_VERSION_MISMATCH: {
    code: 'JAVA_VERSION_MISMATCH',
    owner: 'build',
    category: 'environment',
    message: "Bulunan Java sürümü uyumluluk profilindeki major sürümle eşleşmiyor.",
    retryable: false,
    suggestedAction: "Profildeki Java major sürümünü kurun; başka bir major ile runtime başlatılmaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  MATERIAL_NOT_ALLOWED: {
    code: 'MATERIAL_NOT_ALLOWED',
    owner: 'bridge',
    category: 'permission',
    message: "Materyal fixture'ın allowed_materials listesinde yok.",
    retryable: false,
    suggestedAction: "fixture_inspect ile izin verilen materyalleri okuyun.",
    protocolError: false,
    httpStatus: 403,
    redactionProfile: 'none',
    terminalState: null,
  },
  MUTATION_UNKNOWN_OUTCOME: {
    code: 'MUTATION_UNKNOWN_OUTCOME',
    owner: 'bridge',
    category: 'integrity',
    message: "Mutation'ın uygulanıp uygulanmadığı belirlenemedi.",
    retryable: false,
    suggestedAction: "Kör retry YAPMAYIN. Aynı idempotency key ile mutation durumunu sorgulayın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: 'UNKNOWN_OUTCOME',
  },
  MVN_DISTRIBUTION_CHECKSUM_INVALID: {
    code: 'MVN_DISTRIBUTION_CHECKSUM_INVALID',
    owner: 'maven',
    category: 'integrity',
    message: "Maven dağıtımının checksum'ı beklenen değerle eşleşmiyor.",
    retryable: false,
    suggestedAction: "Dağıtımı yeniden indirin ve resmî checksum ile karşılaştırın; eşleşmeyen dağıtım kullanılmaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  MVN_DISTRIBUTION_CHECKSUM_MISSING: {
    code: 'MVN_DISTRIBUTION_CHECKSUM_MISSING',
    owner: 'maven',
    category: 'integrity',
    message: "distributionSha256Sum tanımlı değil.",
    retryable: false,
    suggestedAction: "maven-wrapper.properties dosyasına distributionSha256Sum ekleyin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  MVN_DISTRIBUTION_URL_UNAPPROVED: {
    code: 'MVN_DISTRIBUTION_URL_UNAPPROVED',
    owner: 'maven',
    category: 'permission',
    message: "distributionUrl allowlist dışında.",
    retryable: false,
    suggestedAction: "distributionUrl değerini repo.maven.apache.org üzerindeki resmî dağıtıma çevirin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  MVN_VERSION_INCOMPATIBLE: {
    code: 'MVN_VERSION_INCOMPATIBLE',
    owner: 'maven',
    category: 'validation',
    message: "Wrapper sürümü uyumluluk profilindeki sürümle eşleşmiyor.",
    retryable: false,
    suggestedAction: "Wrapper'ı profildeki Maven sürümüne güncelleyin; release profili farklı sürüme izin vermez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  MVN_WRAPPER_JAR_UNVERIFIED: {
    code: 'MVN_WRAPPER_JAR_UNVERIFIED',
    owner: 'maven',
    category: 'integrity',
    message: "maven-wrapper.jar checksum doğrulaması başarısız.",
    retryable: false,
    suggestedAction: "Wrapper'ı resmî Maven dağıtımından yeniden üretin; doğrulanmamış wrapper JAR ile build çalıştırılmaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  MVN_WRAPPER_NOT_FOUND: {
    code: 'MVN_WRAPPER_NOT_FOUND',
    owner: 'maven',
    category: 'not_found',
    message: "Maven Wrapper dosyaları bulunamadı.",
    retryable: false,
    suggestedAction: "mvnw, mvnw.cmd ve maven-wrapper.properties dosyalarını projeye ekleyin; yalnızca wrapper desteklenir.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  OPERATION_NOT_CANCELLABLE: {
    code: 'OPERATION_NOT_CANCELLABLE',
    owner: 'supervisor',
    category: 'conflict',
    message: "Operation zaten terminal durumda veya iptali desteklenmiyor.",
    retryable: false,
    suggestedAction: "operation_get ile mevcut durumu okuyun; terminal durumdaki operation iptal edilemez.",
    protocolError: false,
    httpStatus: 409,
    redactionProfile: 'none',
    terminalState: null,
  },
  OPERATION_NOT_FOUND: {
    code: 'OPERATION_NOT_FOUND',
    owner: 'supervisor',
    category: 'not_found',
    message: "Belirtilen operation kaydı bulunamadı.",
    retryable: false,
    suggestedAction: "operation_id değerini doğrulayın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  OUTPUT_LIMIT_EXCEEDED: {
    code: 'OUTPUT_LIMIT_EXCEEDED',
    owner: 'mcp',
    category: 'limit',
    message: "Yanıt yapılandırılmış byte limitini aşıyor.",
    retryable: false,
    suggestedAction: "Cursor veya daha dar bir aralık kullanarak sorguyu bölün.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: null,
  },
  PAPER_JAR_CHECKSUM_INVALID: {
    code: 'PAPER_JAR_CHECKSUM_INVALID',
    owner: 'runtime',
    category: 'integrity',
    message: "Paper JAR checksum'ı runtime image manifest'indeki değerle eşleşmiyor.",
    retryable: false,
    suggestedAction: "Paper JAR'ını resmî Downloads Service üzerinden yeniden indirin; sabit metin URL güvenilmez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  PAPER_PLUGIN_EXPERIMENTAL_DISABLED: {
    code: 'PAPER_PLUGIN_EXPERIMENTAL_DISABLED',
    owner: 'plugin',
    category: 'validation',
    message: "paper-plugin.yml deneysel desteği kapalı.",
    retryable: false,
    suggestedAction: "Deneysel desteği feature flag ile açın veya klasik plugin.yml kullanın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  PARENT_OWNERSHIP_MISMATCH: {
    code: 'PARENT_OWNERSHIP_MISMATCH',
    owner: 'supervisor',
    category: 'integrity',
    message: "Silinecek dizinin üst dizin sahipliği doğrulanamadı.",
    retryable: false,
    suggestedAction: "Runtime kökü yapılandırmasını kontrol edin; silme dry-run validation olmadan başlamaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: null,
  },
  PATH_OUTSIDE_ROOT: {
    code: 'PATH_OUTSIDE_ROOT',
    owner: 'project',
    category: 'permission',
    message: "Çözümlenen yol kayıtlı kökün dışında.",
    retryable: false,
    suggestedAction: "Yolu kayıtlı proje kökü altında tutun; canonical çözümleme sonrası kaçış engellenir.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: null,
  },
  PERMISSION_PROVIDER_UNSUPPORTED: {
    code: 'PERMISSION_PROVIDER_UNSUPPORTED',
    owner: 'plugin',
    category: 'environment',
    message: "Belirtilen permission provider için adapter yok.",
    retryable: false,
    suggestedAction: "native-paper permission provider kullanın; LuckPerms/Vault otomatik varsayılmaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  PLAYER_NOT_FOUND: {
    code: 'PLAYER_NOT_FOUND',
    owner: 'bridge',
    category: 'not_found',
    message: "Belirtilen test oyuncusu bağlı değil.",
    retryable: false,
    suggestedAction: "test_actor.create adımının tamamlandığını doğrulayın.",
    protocolError: false,
    httpStatus: 404,
    redactionProfile: 'strict-v1',
    terminalState: null,
  },
  PLUGIN_API_VERSION_INCOMPATIBLE: {
    code: 'PLUGIN_API_VERSION_INCOMPATIBLE',
    owner: 'plugin',
    category: 'validation',
    message: "plugin.yml api-version değeri hedef Paper sürümüyle uyumsuz.",
    retryable: false,
    suggestedAction: "api-version, Paper build ve Paper API koordinatını birbiriyle tutarlı hâle getirin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  PLUGIN_API_VERSION_MISSING: {
    code: 'PLUGIN_API_VERSION_MISSING',
    owner: 'plugin',
    category: 'validation',
    message: "plugin.yml içinde api-version tanımlı değil.",
    retryable: false,
    suggestedAction: "api-version alanını uyumluluk profilindeki Paper API sürümüne göre ekleyin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  PLUGIN_CONTRACT_ARGUMENT_INVALID: {
    code: 'PLUGIN_CONTRACT_ARGUMENT_INVALID',
    owner: 'plugin',
    category: 'validation',
    message: "Command argümanları test contract şemasına uymuyor.",
    retryable: false,
    suggestedAction: "Argümanları command'in arguments şemasına göre düzeltin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: null,
  },
  PLUGIN_CONTRACT_COMMAND_UNKNOWN: {
    code: 'PLUGIN_CONTRACT_COMMAND_UNKNOWN',
    owner: 'plugin',
    category: 'validation',
    message: "Belirtilen command_id test contract'ında tanımlı değil.",
    retryable: false,
    suggestedAction: "command_id değerini test contract'taki commands anahtarlarından seçin; raw command string kabul edilmez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  PLUGIN_CONTRACT_NOT_FOUND: {
    code: 'PLUGIN_CONTRACT_NOT_FOUND',
    owner: 'plugin',
    category: 'not_found',
    message: "Projede .mcp-minecraft/test-contract.yaml bulunamadı.",
    retryable: false,
    suggestedAction: "Typed command ve mesaj assertion'ları için test contract ekleyin; manifest olmadan generic testler yine çalışır.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  PLUGIN_DEPENDENCY_UNSATISFIED: {
    code: 'PLUGIN_DEPENDENCY_UNSATISFIED',
    owner: 'plugin',
    category: 'state',
    message: "Bir zorunlu plugin bağımlılığı runtime'da mevcut değil.",
    retryable: false,
    suggestedAction: "Bağımlılığı test_dependencies.required altında bildirin veya plugin.yml depend listesini düzeltin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  PLUGIN_ENABLE_FAILED: {
    code: 'PLUGIN_ENABLE_FAILED',
    owner: 'runtime',
    category: 'internal',
    message: "Hedef plugin enable aşamasında hata üretti.",
    retryable: false,
    suggestedAction: "evidence_get ile startup loglarını inceleyin; plugin'in onEnable istisnasını düzeltin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: 'FAILED',
  },
  PLUGIN_LOADING_CYCLE: {
    code: 'PLUGIN_LOADING_CYCLE',
    owner: 'plugin',
    category: 'conflict',
    message: "Plugin yükleme sırasında döngüsel bağımlılık tespit edildi.",
    retryable: false,
    suggestedAction: "depend / softdepend / loadbefore ilişkilerindeki döngüyü kırın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  PLUGIN_MAIN_CLASS_MISSING: {
    code: 'PLUGIN_MAIN_CLASS_MISSING',
    owner: 'plugin',
    category: 'validation',
    message: "plugin.yml içindeki main sınıfı JAR içinde bulunamadı.",
    retryable: false,
    suggestedAction: "main değerini tam sınıf adıyla düzeltin ve JAR'ın sınıfı içerdiğini doğrulayın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  PLUGIN_METADATA_AMBIGUOUS: {
    code: 'PLUGIN_METADATA_AMBIGUOUS',
    owner: 'plugin',
    category: 'conflict',
    message: "Birden fazla plugin metadata dosyası bulundu ve öncelik belirlenemedi.",
    retryable: false,
    suggestedAction: "Açık manifest politikası belirleyin; örtük öncelik kuralı yoktur.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  PLUGIN_METADATA_NOT_FOUND: {
    code: 'PLUGIN_METADATA_NOT_FOUND',
    owner: 'plugin',
    category: 'not_found',
    message: "JAR içinde plugin.yml bulunamadı.",
    retryable: false,
    suggestedAction: "src/main/resources/plugin.yml dosyasını ekleyin; V1'in resmî desteği klasik plugin.yml içindir.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  PLUGIN_NAME_CONFLICT: {
    code: 'PLUGIN_NAME_CONFLICT',
    owner: 'plugin',
    category: 'conflict',
    message: "Aynı plugin adı birden fazla JAR tarafından kullanılıyor.",
    retryable: false,
    suggestedAction: "Çakışan plugin adlarından birini değiştirin veya çakışan test dependency'yi kaldırın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'FAILED',
  },
  PLUGIN_NOT_FOUND: {
    code: 'PLUGIN_NOT_FOUND',
    owner: 'bridge',
    category: 'not_found',
    message: "Belirtilen plugin runtime'da yüklü değil.",
    retryable: false,
    suggestedAction: "minecraft_plugin_list ile yüklü plugin'leri listeleyin.",
    protocolError: false,
    httpStatus: 404,
    redactionProfile: 'none',
    terminalState: null,
  },
  PORT_STILL_BOUND: {
    code: 'PORT_STILL_BOUND',
    owner: 'runtime',
    category: 'integrity',
    message: "Runtime kapandıktan sonra port hâlâ bağlı.",
    retryable: true,
    suggestedAction: "Cleanup kanıtını inceleyin; kalan process için Supervisor recovery çalıştırın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'DIRTY',
  },
  PORT_UNAVAILABLE: {
    code: 'PORT_UNAVAILABLE',
    owner: 'runtime',
    category: 'environment',
    message: "Uygun bir port bulunamadı.",
    retryable: true,
    suggestedAction: "Kalan runtime'ları serbest bırakın; port çakışması için runtime_get çıktısını inceleyin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  PROCESS_OWNERSHIP_MISMATCH: {
    code: 'PROCESS_OWNERSHIP_MISMATCH',
    owner: 'supervisor',
    category: 'integrity',
    message: "Kayıtlı process kimliği çalışan process ile eşleşmiyor; sonlandırma yapılmadı.",
    retryable: false,
    suggestedAction: "Supervisor startup recovery çalıştırın; bilinmeyen PID körlemesine öldürülmez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: 'ORPHANED',
  },
  PROJECT_NOT_REGISTERED: {
    code: 'PROJECT_NOT_REGISTERED',
    owner: 'project',
    category: 'not_found',
    message: "Bu project_id kayıtlı değil.",
    retryable: false,
    suggestedAction: "Projeyi ürün config'inde kaydedin; araçlar mutlak path kabul etmez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  PROVISIONING_APPROVAL_REQUIRED: {
    code: 'PROVISIONING_APPROVAL_REQUIRED',
    owner: 'build',
    category: 'permission',
    message: "Provisioning modu açık kullanıcı onayı gerektirir.",
    retryable: false,
    suggestedAction: "Provisioning'i onaylı workflow üzerinden çalıştırın; ağ erişimi gerektiren tek mod budur ve Container zorunludur.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  READY_GATE_FAILED: {
    code: 'READY_GATE_FAILED',
    owner: 'runtime',
    category: 'state',
    message: "Ready gate geçilemedi.",
    retryable: false,
    suggestedAction: "plugin_diagnose çalıştırın; ready gate Paper hazır + Bridge boot_id + hedef plugin enabled şartlarının üçünü gerektirir.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: 'FAILED',
  },
  REGION_NOT_ALLOWED: {
    code: 'REGION_NOT_ALLOWED',
    owner: 'bridge',
    category: 'permission',
    message: "Konum fixture bölgesinin dışında.",
    retryable: false,
    suggestedAction: "fixture_inspect ile izin verilen bölge sınırlarını okuyun; bölge dışı yazma yapılamaz.",
    protocolError: false,
    httpStatus: 403,
    redactionProfile: 'none',
    terminalState: null,
  },
  RESOURCE_NOT_FOUND: {
    code: 'RESOURCE_NOT_FOUND',
    owner: 'mcp',
    category: 'not_found',
    message: "İstenen resource mevcut değil veya retention süresi dolmuş.",
    retryable: false,
    suggestedAction: "Resource URI'sini ve run kimliğini doğrulayın; silinmiş resource geri getirilemez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  RUN_NOT_FOUND: {
    code: 'RUN_NOT_FOUND',
    owner: 'supervisor',
    category: 'not_found',
    message: "Belirtilen run kaydı bulunamadı.",
    retryable: false,
    suggestedAction: "run_id değerini doğrulayın; retention süresi geçmiş run'lar silinmiş olabilir.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  RUNTIME_CRASHED: {
    code: 'RUNTIME_CRASHED',
    owner: 'runtime',
    category: 'internal',
    message: "Paper process beklenmedik biçimde sonlandı.",
    retryable: false,
    suggestedAction: "evidence_get ile runtime loglarını ve crash kanıtını inceleyin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: 'FAILED',
  },
  RUNTIME_INVALID_STATE: {
    code: 'RUNTIME_INVALID_STATE',
    owner: 'runtime',
    category: 'state',
    message: "Runtime bu operation için uygun durumda değil.",
    retryable: false,
    suggestedAction: "runtime_get ile mevcut durumu okuyun ve durum makinesine uygun geçişi çağırın.",
    protocolError: false,
    httpStatus: 409,
    redactionProfile: 'none',
    terminalState: null,
  },
  RUNTIME_MARKER_MISSING: {
    code: 'RUNTIME_MARKER_MISSING',
    owner: 'runtime',
    category: 'integrity',
    message: "Runtime marker dosyası bulunamadı; dizin bize ait olarak doğrulanamadı.",
    retryable: false,
    suggestedAction: "Dizini elle silmeyin; Garbage Collector marker olmadan silme yapmaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: null,
  },
  RUNTIME_NOT_FOUND: {
    code: 'RUNTIME_NOT_FOUND',
    owner: 'runtime',
    category: 'not_found',
    message: "Belirtilen runtime kaydı bulunamadı.",
    retryable: false,
    suggestedAction: "runtime kimliğini doğrulayın; retention süresi geçmiş runtime'lar silinmiş olabilir.",
    protocolError: false,
    httpStatus: 404,
    redactionProfile: 'none',
    terminalState: null,
  },
  RUNTIME_NOT_RUNNING: {
    code: 'RUNTIME_NOT_RUNNING',
    owner: 'runtime',
    category: 'state',
    message: "Runtime çalışmıyor.",
    retryable: false,
    suggestedAction: "Önce plugin_launch işlemini tamamlayın.",
    protocolError: false,
    httpStatus: 409,
    redactionProfile: 'none',
    terminalState: null,
  },
  RUNTIME_QUOTA_EXCEEDED: {
    code: 'RUNTIME_QUOTA_EXCEEDED',
    owner: 'supervisor',
    category: 'limit',
    message: "Eşzamanlı runtime limiti aşıldı.",
    retryable: true,
    suggestedAction: "Mevcut runtime'ları plugin_stop ve runtime_release ile serbest bırakın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  SCENARIO_SCHEMA_INVALID: {
    code: 'SCENARIO_SCHEMA_INVALID',
    owner: 'scenario',
    category: 'validation',
    message: "Scenario dosyası DSL şemasına uymuyor.",
    retryable: false,
    suggestedAction: "scenario_validate çıktısındaki şema hatalarını düzeltin; custom YAML tag ve include kullanılamaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: null,
  },
  SCENARIO_STEP_LIMIT_EXCEEDED: {
    code: 'SCENARIO_STEP_LIMIT_EXCEEDED',
    owner: 'scenario',
    category: 'limit',
    message: "Scenario maksimum step sayısını aşıyor.",
    retryable: false,
    suggestedAction: "Scenario'yu daha küçük, tek amaçlı scenario'lara bölün.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  SCENARIO_STEP_NOT_ALLOWED: {
    code: 'SCENARIO_STEP_NOT_ALLOWED',
    owner: 'scenario',
    category: 'permission',
    message: "Kullanılan step allowlist'te yok.",
    retryable: false,
    suggestedAction: "scenario_step_catalog ile izin verilen step listesini alın; raw command string kabul edilmez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  SCENARIO_TIMEOUT: {
    code: 'SCENARIO_TIMEOUT',
    owner: 'scenario',
    category: 'timeout',
    message: "Scenario süre limitini aştı.",
    retryable: false,
    suggestedAction: "Assertion'ların within değerlerini gözden geçirin; sabit uyku yerine eventual assertion kullanın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: 'TIMED_OUT',
  },
  SHUTDOWN_TIMEOUT: {
    code: 'SHUTDOWN_TIMEOUT',
    owner: 'runtime',
    category: 'timeout',
    message: "Graceful shutdown süre limitini aştı; force termination uygulandı.",
    retryable: false,
    suggestedAction: "Cleanup kanıtındaki force_terminated alanını inceleyin; plugin'in onDisable davranışını kontrol edin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  SOURCE_CHANGED_DURING_BUILD: {
    code: 'SOURCE_CHANGED_DURING_BUILD',
    owner: 'project',
    category: 'integrity',
    message: "Kaynak workspace build sırasında değişti; snapshot artık geçerli değil.",
    retryable: true,
    suggestedAction: "Dosya değişikliklerini durdurup build'i yeni bir snapshot ile tekrarlayın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: 'FAILED',
  },
  STARTUP_TIMEOUT: {
    code: 'STARTUP_TIMEOUT',
    owner: 'runtime',
    category: 'timeout',
    message: "Paper startup süre limitini aştı.",
    retryable: true,
    suggestedAction: "runtime.startup_timeout_seconds değerini artırın veya runtime loglarında takılma noktasını inceleyin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: 'TIMED_OUT',
  },
  SUPERVISOR_UNAVAILABLE: {
    code: 'SUPERVISOR_UNAVAILABLE',
    owner: 'supervisor',
    category: 'environment',
    message: "Run Supervisor process'ine ulaşılamıyor.",
    retryable: true,
    suggestedAction: "Supervisor process'inin çalıştığını doğrulayın; system_health çıktısındaki supervisor alanını kontrol edin.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: null,
  },
  SYMLINK_NOT_ALLOWED: {
    code: 'SYMLINK_NOT_ALLOWED',
    owner: 'project',
    category: 'permission',
    message: "Symlink, junction veya reparse point reddedildi.",
    retryable: false,
    suggestedAction: "Bağlantıyı kaldırın veya gerçek dizini kaydedin; symlink varsayılan olarak reddedilir.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'strict-v1',
    terminalState: null,
  },
  TOOL_INPUT_INVALID: {
    code: 'TOOL_INPUT_INVALID',
    owner: 'mcp',
    category: 'validation',
    message: "Tool girdisi şemaya uymuyor.",
    retryable: false,
    suggestedAction: "Tool'un inputSchema'sına göre argümanları düzeltin; mutlak path kabul edilmez.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'default-v1',
    terminalState: null,
  },
  TRUST_LEVEL_INSUFFICIENT: {
    code: 'TRUST_LEVEL_INSUFFICIENT',
    owner: 'project',
    category: 'permission',
    message: "Projenin trust seviyesi bu operation için yetersiz.",
    retryable: false,
    suggestedAction: "Trust seviyesini kullanıcı olarak yükseltin; trust kaydı proje klasörünün içinde tutulmaz.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  UNAPPROVED_REPOSITORY: {
    code: 'UNAPPROVED_REPOSITORY',
    owner: 'gradle',
    category: 'permission',
    message: "Repository allowlist dışında.",
    retryable: false,
    suggestedAction: "Repository'yi build.repository_allowlist listesine ekleyin veya bağımlılığı onaylı bir kaynaktan alın.",
    protocolError: false,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  UNKNOWN_TOOL: {
    code: 'UNKNOWN_TOOL',
    owner: 'mcp',
    category: 'validation',
    message: "İstenen tool bu profilde tanımlı değil.",
    retryable: false,
    suggestedAction: "system_capabilities ile aktif profildeki tool listesini alın.",
    protocolError: true,
    httpStatus: null,
    redactionProfile: 'none',
    terminalState: null,
  },
  WORLD_NOT_FOUND: {
    code: 'WORLD_NOT_FOUND',
    owner: 'bridge',
    category: 'not_found',
    message: "Belirtilen dünya yüklü değil.",
    retryable: false,
    suggestedAction: "minecraft_world_list ile yüklü dünyaları listeleyin.",
    protocolError: false,
    httpStatus: 404,
    redactionProfile: 'none',
    terminalState: null,
  },
} as const;
